sudo: false
before_script:
  - curl -LSfs https://japaric.github.io/trust/install.sh |
    sh -s --
    --git cobalt-org/cobalt.rs
    --crate cobalt
    --force
    --target x86_64-unknown-linux-gnu
    --tag v0.12.2
  - export PATH="$PATH:~/.cargo/bin"
script:
  - cobalt build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
env:
  global:
    secure: p0fuQrMWPogtiPuulwvNy/vqbgPKhWdW7H5P9W1cW/KQUimCIGLh2+vg+8rOcfgkbJ0TRZAo2CV2bIq4TotVwYIje1pnAV4DC+NQldU1prX0MjveXQVAeIEi+0sdrSQbw6UWRHjHDw7cTEXq3SeRk1CmfocmbMoLRTfyxnGe31OqQdGqwTUb9X/bYNs7KRuvhEF3kTPWHtI2utYal5gysgAANcuwsPXR6Qkgoo1tVcsZc4+kbJiuJc/xq3ZqzER8bZ1Rmh4ZqtX+oT5Yr+BrnBYFsxs1qD0B2mIwqey3cYJrMZYtcX1kzmGDCzHOcqNag5SZy8YO5pVmdAed/KDQc8WIFHLsP9JstvCvG8rmDhtqEkyH+CBm/zznq3IB9IvZKZknAMO3SB1gHnCqb8nv/jCzUxh1ly6pNFSULiBT2aom2mWZp4jQ3WXOT+ivTAaCs58KbU+vRW6CxV/8QYSwCkOolRsgPQy3YVVPWuIO3QA5I/ejfvIw+QooreZxtqYP59d87wV2ezfbBz70Kk6FbXjvu0Eg/lwini5bp0QNNvYhKszm1W8rCa60y2LPOumDrLWMmm+vVpmhjoTVuOf8Ozjd6ECroLxDXTQI+vi8B1xgiaam0ZiVygd1zgn9YOyvmfDRkLisu9XKh/sxl3WWePx/zFgP3bMBgTrVWWuru2Y=
